Partial rgb support
fabiocaccamo/django-colorfield pull request #84
Opened 2022-10-09 09:12 UTC by hertzdude

2022-10-09 12:19 UTC, fabiocaccamo requested changes

2022-10-09 12:19 UTC, fabiocaccamo commented on colorfield/validators.py
> +COLOR_RGB_RE = re_compile("(#([\da-f]{3}){1,2}|(rgb|hsl)a\((\d{1,3}%?,\s?){3}(1|0?\.\d+)\)|(rgb|hsl)\(\d{1,3}%?(,\s?\d{1,3}%?){2}\))")
This regular expression is too complex for doing just RGB colors validation.

2022-10-09 12:22 UTC, fabiocaccamo requested changes
1. If we add RGB colors support, we should add also RGBA colors support.
2. The PR doesn't pass tests.

2022-10-09 18:01 UTC, hertzdude commented
OK, I'll do it within a couple of days.

2022-10-23 08:25 UTC, fabiocaccamo commented
@hertzdude any update?

2022-11-14 10:43 UTC, closed without merging